extern const GeoLayout sslstar_geo[];
extern Lights1 sslstar_f3dlite_material_lights;
extern u8 sslstar__6_ci8[];
extern u8 sslstar__6_pal_rgba16[];
extern u8 sslstar_eye_ia8[];
extern Vtx sslstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx sslstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx sslstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx sslstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_sslstar_f3dlite_material_037[];
extern Gfx mat_revert_sslstar_f3dlite_material_037[];
extern Gfx mat_sslstar_f3dlite_material[];
extern Gfx mat_revert_sslstar_f3dlite_material[];
extern Gfx sslstar_000_displaylist_mesh_layer_1[];
extern Gfx sslstar_001_displaylist_mesh_layer_5[];
