extern const GeoLayout stargrey_geo[];
extern Lights1 stargrey_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 stargrey_eye_rgba16[];
extern u8 stargrey__11_ci8[];
extern u8 stargrey__11_ci8_pal_rgba16[];
extern Vtx stargrey_star_mesh_layer_5_vtx_0[8];
extern Gfx stargrey_star_mesh_layer_5_tri_0[];
extern Vtx stargrey_star_mesh_layer_1_vtx_0[12];
extern Gfx stargrey_star_mesh_layer_1_tri_0[];
extern Gfx mat_stargrey_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_stargrey_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_stargrey_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_stargrey_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx stargrey_star_mesh_layer_5[];
extern Gfx stargrey_star_mesh_layer_1[];
extern Gfx stargrey_material_revert_render_settings[];
