extern const GeoLayout stargreen_geo[];
extern Lights1 stargreen_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 stargreen_eye_rgba16[];
extern u8 stargreen__9_ci8[];
extern u8 stargreen__9_ci8_pal_rgba16[];
extern Vtx stargreen_star_mesh_layer_5_vtx_0[8];
extern Gfx stargreen_star_mesh_layer_5_tri_0[];
extern Vtx stargreen_star_mesh_layer_1_vtx_0[12];
extern Gfx stargreen_star_mesh_layer_1_tri_0[];
extern Gfx mat_stargreen_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_stargreen_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_stargreen_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_stargreen_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx stargreen_star_mesh_layer_5[];
extern Gfx stargreen_star_mesh_layer_1[];
extern Gfx stargreen_material_revert_render_settings[];
