extern const GeoLayout dddstar_geo[];
extern Lights1 dddstar_f3dlite_material_lights;
extern u8 dddstar__13_ci8[];
extern u8 dddstar__13_pal_rgba16[];
extern u8 dddstar_eye_ia8[];
extern Vtx dddstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx dddstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx dddstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx dddstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_dddstar_f3dlite_material_037[];
extern Gfx mat_revert_dddstar_f3dlite_material_037[];
extern Gfx mat_dddstar_f3dlite_material[];
extern Gfx mat_revert_dddstar_f3dlite_material[];
extern Gfx dddstar_000_displaylist_mesh_layer_1[];
extern Gfx dddstar_001_displaylist_mesh_layer_5[];
