extern const GeoLayout rrstar_geo[];
extern Lights1 rrstar_f3dlite_material_lights;
extern u8 rrstar__7_ci8[];
extern u8 rrstar__7_pal_rgba16[];
extern u8 rrstar_eye_ia8[];
extern Vtx rrstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx rrstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx rrstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx rrstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_rrstar_f3dlite_material_037[];
extern Gfx mat_revert_rrstar_f3dlite_material_037[];
extern Gfx mat_rrstar_f3dlite_material[];
extern Gfx mat_revert_rrstar_f3dlite_material[];
extern Gfx rrstar_000_displaylist_mesh_layer_1[];
extern Gfx rrstar_001_displaylist_mesh_layer_5[];
