extern const GeoLayout ttcstar_geo[];
extern Lights1 ttcstar_f3dlite_material_lights;
extern u8 ttcstar__11_ci8[];
extern u8 ttcstar__11_pal_rgba16[];
extern u8 ttcstar_eye_ia8[];
extern Vtx ttcstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx ttcstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx ttcstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx ttcstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_ttcstar_f3dlite_material_037[];
extern Gfx mat_revert_ttcstar_f3dlite_material_037[];
extern Gfx mat_ttcstar_f3dlite_material[];
extern Gfx mat_revert_ttcstar_f3dlite_material[];
extern Gfx ttcstar_000_displaylist_mesh_layer_1[];
extern Gfx ttcstar_001_displaylist_mesh_layer_5[];
