extern const GeoLayout starpurple_geo[];
extern Lights1 starpurple_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 starpurple_eye_rgba16[];
extern u8 starpurple__4_ci8[];
extern u8 starpurple__4_ci8_pal_rgba16[];
extern Vtx starpurple_star_mesh_layer_5_vtx_0[8];
extern Gfx starpurple_star_mesh_layer_5_tri_0[];
extern Vtx starpurple_star_mesh_layer_1_vtx_0[12];
extern Gfx starpurple_star_mesh_layer_1_tri_0[];
extern Gfx mat_starpurple_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_starpurple_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_starpurple_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_starpurple_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx starpurple_star_mesh_layer_5[];
extern Gfx starpurple_star_mesh_layer_1[];
extern Gfx starpurple_material_revert_render_settings[];
