extern const GeoLayout moving_cloud.geo[];
extern Lights1 Moving_Cloud_f3dlite_material_cloud_sides_001_lights;
extern Lights1 Moving_Cloud_f3dlite_material_cloud_bottom_001_lights;
extern Lights1 Moving_Cloud_f3dlite_material_cloud_top_001_lights;
extern u8 Moving_Cloud_badtexture2_i8[];
extern u8 Moving_Cloud_badtexture_i8[];
extern u8 Moving_Cloud__2_rgba16_i8[];
extern Vtx Moving_Cloud_Moving_Cloud_mesh_layer_1_vtx_0[16];
extern Gfx Moving_Cloud_Moving_Cloud_mesh_layer_1_tri_0[];
extern Vtx Moving_Cloud_Moving_Cloud_mesh_layer_1_vtx_1[4];
extern Gfx Moving_Cloud_Moving_Cloud_mesh_layer_1_tri_1[];
extern Vtx Moving_Cloud_Moving_Cloud_mesh_layer_1_vtx_2[4];
extern Gfx Moving_Cloud_Moving_Cloud_mesh_layer_1_tri_2[];
extern Gfx mat_Moving Cloud_f3dlite_material_cloud_sides_001[];
extern Gfx mat_Moving Cloud_f3dlite_material_cloud_bottom_001[];
extern Gfx mat_Moving Cloud_f3dlite_material_cloud_top_001[];
extern Gfx Moving_Cloud_Moving_Cloud_mesh_layer_1[];
extern Gfx Moving Cloud_material_revert_render_settings[];
