extern const GeoLayout hmcstar_geo[];
extern Lights1 hmcstar_f3dlite_material_lights;
extern u8 hmcstar__2_ci8[];
extern u8 hmcstar__2_pal_rgba16[];
extern u8 hmcstar_eye_ia8[];
extern Vtx hmcstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx hmcstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx hmcstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx hmcstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_hmcstar_f3dlite_material_037[];
extern Gfx mat_revert_hmcstar_f3dlite_material_037[];
extern Gfx mat_hmcstar_f3dlite_material[];
extern Gfx mat_revert_hmcstar_f3dlite_material[];
extern Gfx hmcstar_000_displaylist_mesh_layer_1[];
extern Gfx hmcstar_001_displaylist_mesh_layer_5[];
