extern const GeoLayout staryellow_geo[];
extern Lights1 staryellow_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 staryellow_eye_rgba16[];
extern u8 staryellow__8_ci8[];
extern u8 staryellow__8_ci8_pal_rgba16[];
extern Vtx staryellow_star_mesh_layer_5_vtx_0[8];
extern Gfx staryellow_star_mesh_layer_5_tri_0[];
extern Vtx staryellow_star_mesh_layer_1_vtx_0[12];
extern Gfx staryellow_star_mesh_layer_1_tri_0[];
extern Gfx mat_staryellow_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_staryellow_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_staryellow_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_staryellow_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx staryellow_star_mesh_layer_5[];
extern Gfx staryellow_star_mesh_layer_1[];
extern Gfx staryellow_material_revert_render_settings[];
