extern const GeoLayout starbluered_geo[];
extern Lights1 starbluered_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 starbluered_eye_rgba16[];
extern u8 starbluered__12_rgba16[];
extern Vtx starbluered_star_mesh_layer_5_vtx_0[8];
extern Gfx starbluered_star_mesh_layer_5_tri_0[];
extern Vtx starbluered_star_mesh_layer_1_vtx_0[12];
extern Gfx starbluered_star_mesh_layer_1_tri_0[];
extern Gfx mat_starbluered_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_starbluered_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_starbluered_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_starbluered_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx starbluered_star_mesh_layer_5[];
extern Gfx starbluered_star_mesh_layer_1[];
extern Gfx starbluered_material_revert_render_settings[];
