extern const GeoLayout starblack_geo[];
extern Lights1 starblack_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 starblack_eye_rgba16[];
extern u8 starblack__14_i8[];
extern Vtx starblack_star_mesh_layer_5_vtx_0[8];
extern Gfx starblack_star_mesh_layer_5_tri_0[];
extern Vtx starblack_star_mesh_layer_1_vtx_0[12];
extern Gfx starblack_star_mesh_layer_1_tri_0[];
extern Gfx mat_starblack_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_starblack_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_starblack_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_starblack_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx starblack_star_mesh_layer_5[];
extern Gfx starblack_star_mesh_layer_1[];
extern Gfx starblack_material_revert_render_settings[];
