extern const GeoLayout lllstar_geo[];
extern Lights1 lllstar_f3dlite_material_lights;
extern u8 lllstar__5_ci8[];
extern u8 lllstar__5_pal_rgba16[];
extern u8 lllstar_eye_ia8[];
extern Vtx lllstar_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx lllstar_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx lllstar_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx lllstar_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_lllstar_f3dlite_material_037[];
extern Gfx mat_revert_lllstar_f3dlite_material_037[];
extern Gfx mat_lllstar_f3dlite_material[];
extern Gfx mat_revert_lllstar_f3dlite_material[];
extern Gfx lllstar_000_displaylist_mesh_layer_1[];
extern Gfx lllstar_001_displaylist_mesh_layer_5[];
