#ifndef PSS_HEADER_H
#define PSS_HEADER_H
#include "types.h"
#include "game/moving_texture.h"
extern const GeoLayout Geo_pss_1_0x23a7540[];
extern Gfx DL_pss_1_0xe00be00[];
extern Gfx DL_pss_1_0xe00cc08[];
extern const Collision col_pss_1_0xe00cf40[];
extern struct MovtexQuadCollection pss_1_Movtex_0[];
extern struct MovtexQuadCollection pss_1_Movtex_1[];
extern struct MovtexQuadCollection pss_1_Movtex_2[];
extern const GeoLayout Geo_pss_2_0x23a7430[];
extern Gfx DL_pss_2_0xe006580[];
extern Gfx DL_pss_2_0xe006e58[];
extern const Collision col_pss_2_0xe007150[];
extern struct MovtexQuadCollection pss_2_Movtex_0[];
extern struct MovtexQuadCollection pss_2_Movtex_1[];
extern struct MovtexQuadCollection pss_2_Movtex_2[];
extern const GeoLayout Geo_pss_3_0x23a7100[];
extern Gfx DL_pss_3_0xe020e60[];
extern Gfx DL_pss_3_0xe028a78[];
extern const Collision col_pss_3_0xe028d80[];
extern struct MovtexQuadCollection pss_3_Movtex_0[];
extern struct MovtexQuadCollection pss_3_Movtex_1[];
extern struct MovtexQuadCollection pss_3_Movtex_2[];
extern const GeoLayout Geo_pss_5_0x23a7320[];
extern Gfx DL_pss_5_0xe005dd0[];
extern Gfx DL_pss_5_0xe006628[];
extern const Collision col_pss_5_0xe006890[];
extern struct MovtexQuadCollection pss_5_Movtex_0[];
extern struct MovtexQuadCollection pss_5_Movtex_1[];
extern struct MovtexQuadCollection pss_5_Movtex_2[];
extern const GeoLayout Geo_pss_6_0x23a7210[];
extern Gfx DL_pss_6_0xe007c60[];
extern Gfx DL_pss_6_0xe008538[];
extern const Collision col_pss_6_0xe008a60[];
extern struct MovtexQuadCollection pss_6_Movtex_0[];
extern struct MovtexQuadCollection pss_6_Movtex_1[];
extern struct MovtexQuadCollection pss_6_Movtex_2[];
extern const LevelScript level_pss_custom_entry[];
extern const LevelScript local_area_pss_1_[];
extern const LevelScript local_objects_pss_1_[];
extern const LevelScript local_warps_pss_1_[];
extern const LevelScript local_area_pss_2_[];
extern const LevelScript local_objects_pss_2_[];
extern const LevelScript local_warps_pss_2_[];
extern const LevelScript local_area_pss_3_[];
extern const LevelScript local_objects_pss_3_[];
extern const LevelScript local_warps_pss_3_[];
extern const LevelScript local_area_pss_5_[];
extern const LevelScript local_objects_pss_5_[];
extern const LevelScript local_warps_pss_5_[];
extern const LevelScript local_area_pss_6_[];
extern const LevelScript local_objects_pss_6_[];
extern const LevelScript local_warps_pss_6_[];
extern const LevelScript level_pss_entry[];
extern const GeoLayout pss_geo_000100[];
extern const Gfx pss_seg7_dl_0700A7C0[];
extern const Gfx pss_seg7_dl_0700AFA8[];
extern const Gfx pss_seg7_dl_0700B3F0[];
extern const Gfx pss_seg7_dl_0700D338[];
extern const Gfx pss_seg7_dl_0700DAD8[];
extern const Gfx pss_seg7_dl_0700E2B0[];
extern const Gfx pss_seg7_dl_0700E3E8[];
extern const Collision pss_seg7_collision[];
extern const MacroObject pss_seg7_macro_objs[];
extern const LevelScript level_pss_entry[];
#endif