extern const GeoLayout star_geo[];
extern Lights1 star_f3dlite_material_lights;
extern u8 star__16_rgba16[];
extern u8 star_eye_ia8[];
extern Vtx star_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx star_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx star_001_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx star_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_star_f3dlite_material_037[];
extern Gfx mat_revert_star_f3dlite_material_037[];
extern Gfx mat_star_f3dlite_material[];
extern Gfx mat_revert_star_f3dlite_material[];
extern Gfx star_000_displaylist_mesh_layer_1[];
extern Gfx star_001_displaylist_mesh_layer_5[];
