extern const GeoLayout star_001_displaylist_opt1[];
extern const GeoLayout star_001_displaylist_opt2[];
extern const GeoLayout star_001_displaylist_opt3[];
extern const GeoLayout star_001_displaylist_opt4[];
extern const GeoLayout star_001_displaylist_opt5[];
extern const GeoLayout star_001_displaylist_opt6[];
extern const GeoLayout star_001_displaylist_opt7[];
extern const GeoLayout star_001_displaylist_opt8[];
extern const GeoLayout star_001_displaylist_opt9[];
extern const GeoLayout star_001_displaylist_opt10[];
extern const GeoLayout star_001_displaylist_opt11[];
extern const GeoLayout star_001_displaylist_opt12[];
extern const GeoLayout star_001_displaylist_opt13[];
extern const GeoLayout star_001_displaylist_opt14[];
extern const GeoLayout star_001_displaylist_opt15[];
extern const GeoLayout star_001_displaylist_opt16[];
extern const GeoLayout star_geo[];
extern u8 star__16_rgba16[];
extern Vtx star_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx star_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_star_f3dlite_material_002[];
extern Gfx mat_revert_star_f3dlite_material_002[];
extern Gfx star_000_displaylist_mesh_layer_1[];
