extern const GeoLayout starred_geo[];
extern Lights1 starred_Material_063_3ED452ED_c_bmp_f3d_layer1_lights;
extern u8 starred_eye_rgba16[];
extern u8 starred__6_ci8[];
extern u8 starred__6_ci8_pal_rgba16[];
extern Vtx starred_star_mesh_layer_5_vtx_0[8];
extern Gfx starred_star_mesh_layer_5_tri_0[];
extern Vtx starred_star_mesh_layer_1_vtx_0[12];
extern Gfx starred_star_mesh_layer_1_tri_0[];
extern Gfx mat_starred_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_revert_starred_Material_065_713E77D_c_bmp_f3d[];
extern Gfx mat_starred_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx mat_revert_starred_Material_063_3ED452ED_c_bmp_f3d_layer1[];
extern Gfx starred_star_mesh_layer_5[];
extern Gfx starred_star_mesh_layer_1[];
extern Gfx starred_material_revert_render_settings[];
